#
# MIT License
#
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: fulcio-config
  namespace: fulcio-system
data:
  config.json: |-
    {
      "OIDCIssuers": {
        "https://accounts.google.com": {
          "IssuerURL": "https://accounts.google.com",
          "ClientID": "sigstore",
          "Type": "email"
        },
        "https://oidc.vaikas.dev": {
          "IssuerURL": "https://oidc.vaikas.dev",
          "ClientID": "sigstore",
          "Type": "spiffe"
        },
        "https://token.actions.githubusercontent.com": {
          "IssuerURL": "https://token.actions.githubusercontent.com",
          "ClientID": "sigstore",
          "Type": "github-workflow"
        },
        "https://oauth2.sigstore.dev/auth": {
          "IssuerURL": "https://oauth2.sigstore.dev/auth",
          "ClientID": "sigstore",
          "Type": "email",
          "IssuerClaim": "$.federated_claims.connector_id"
        }
      },
      "MetaIssuers": {
        "https://container.googleapis.com/v1/projects/*/locations/*/clusters/*": {
          "ClientID": "sigstore",
          "Type": "kubernetes"
        },
        "https://oidc.eks.*.amazonaws.com/id/*": {
          "ClientID": "sigstore",
          "Type": "kubernetes"
        },
        "https://oidc.prod-aks.azure.com/*": {
          "ClientID": "sigstore",
          "Type": "kubernetes"
        }
      }
    }
