apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: python-build-pipeline
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: src
    - name: imageUrl
      description: Image name to create including repository
    - name: imageTag
      description: Image tag
    - name: REQUIREMENTSFILE
      description: Requirements file for running pip.
    - name: DOCKERFILE
      description: Dockerfile in the original source repo to use for building the image with.
    - name: fulcio-endpoint
      description: Fulcio endpoint
      default: "http://fulcio.fulcio-system.svc"
    - name: rekor-endpoint
      description: Rekor endpoint
      default: "http://rekor.rekor-system.svc"
  results:
    - name: IMAGES
      description: Digest of the image that was created
      value: $(params.imageUrl)@$(tasks.source-to-image.results.IMAGE-DIGEST)
  workspaces:
    - name: git-source
    - name: dependencies
  tasks:
    - name: fetch-from-git
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: git-source
    - name: install-dependencies
      runAfter:
      - fetch-from-git
      taskRef:
        name: install-python-dependencies
      params:
        - name: REQUIREMENTSFILE
          value: $(params.REQUIREMENTSFILE)
      workspaces:
        - name: source
          workspace: git-source
        - name: dependencies
          workspace: dependencies
    - name: list-dependencies
      runAfter:
      - install-dependencies
      taskRef:
        name: list-dependencies
      workspaces:
        - name: dependencies
          workspace: dependencies
    - name: source-to-image
      taskRef:
        name: kaniko
      runAfter:
        - list-dependencies
      workspaces:
        - name: source
          workspace: dependencies
      params:
        - name: IMAGE
          value: $(params.imageUrl):$(params.imageTag)
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
    - name: generate-sbom
      taskRef:
        name: sbom-syft
      runAfter:
        - source-to-image
      params:
        - name: dev.chainguard.refresher.digest
          value: $(params.imageUrl)@$(tasks.source-to-image.results.IMAGE-DIGEST)
        - name: dev.chainguard.refresher.rekor-endpoint
          value: $(params.rekor-endpoint)
        - name: dev.chainguard.refresher.fulcio-endpoint
          value: $(params.fulcio-endpoint)
    - name: trivy-scan
      taskRef:
        name: scan-trivy
      runAfter:
        - source-to-image
      params:
        - name: dev.chainguard.refresher.digest
          value: $(params.imageUrl)@$(tasks.source-to-image.results.IMAGE-DIGEST)
        - name: dev.chainguard.refresher.rekor-endpoint
          value: $(params.rekor-endpoint)
        - name: dev.chainguard.refresher.fulcio-endpoint
          value: $(params.fulcio-endpoint)

