apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: list-dependencies
spec:
  workspaces:
    - name: dependencies
      description: Where the dependencies are installed into by previous step
  steps:
    - name: list-python-requirements
      image: python:3.10-slim@sha256:ca2a31f21938f24bab02344bf846a90cc2bff5bd0e5a53b24b5dfcb4519ea8a3
      script: |
        cd $(workspaces.dependencies.path)
        ls -R $(workspaces.dependencies.path)
