#
# MIT License
#
# (C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: trillian
  namespace: trillian-system
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: trillian-system
  name: log-signer
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        # LogSigner is stateful service because it gives promises to flush
        # the SCT to persistent store.
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      serviceAccountName: trillian
      containers:
      - name: log-signer
        args: [
        "--mysql_uri=$(MYSQL_USER):$(MYSQL_PASSWORD)@tcp($(DATABASE_HOSTNAME):3306)/$(DATABASE_NAME)",
        "--storage_system=mysql",
        # Either force the master, or use the etcd looks like are the only
        # two options. For now, just use this until we sort etcd stuff out.
        "--force_master",
#        "--etcd_servers=trillian-etcd-cluster-client.etcd-system.svc:2379",
        "--quota_system=mysql",
#        "--etcd_http_service=trillian-logsigner-http",
#        "--http_endpoint=0.0.0.0:8091",
        "--sequencer_guard_window=1s",
        "--sequencer_interval=20ms",
        "--num_sequencers=10",
        "--batch_size=500",
        # No idea what this is...
        # "$(SIGNER_DEQUEUE_BUCKET_FRACTION)",
        "--master_hold_jitter=7200s",
        "--alsologtostderr"
        ]
        env:
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: trillian-client
                key: name
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: trillian-client
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: trillian-client
                key: password
          - name: DATABASE_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: trillian-client
                key: host
        image: gcr.io/projectsigstore/trillian_log_signer@sha256:fe90d523f6617974f70878918e4b31d49b2b46a86024bb2d6b01d2bbfed8edbf 
        ports:
        - name: h2c
          containerPort: 8090
