apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: install-go-dependencies
spec:
  workspaces:
    - name: source
      description: Where the git clones the repo to.
    - name: dependencies
      description: Where the dependencies are installed into
  steps:
    - name: install-go-requirements
      image: golang:1.17.7-bullseye
      env:
        - name: GOMODCACHE
          value: $(workspaces.dependencies.path)/gomod
      script: |
        cd $(workspaces.source.path)
        mkdir $GOMODCACHE
        go mod download
        cp -R $(workspaces.source.path) $(workspaces.dependencies.path)
