apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ko-build-image
spec:
  params:
    - name: MAIN_DIR
      description: Directory containing the main executable (one with main func) to build.
    - name: KO_DOCKER_REPO
      description: Registry to push the image to
  results:
    - name: DIGESTS
      description: Digest of the image just built.
  workspaces:
    - name: source
      description: Where the dependencies and source code are.
  steps:
    - name: ko-build-image
      image: golang:1.17.7-bullseye
      script: |
        cd $(workspaces.source.path)/source
        go install "github.com/google/ko@latest"
        GOMODCACHE=$(workspaces.source.path)/gomod KO_DOCKER_REPO=$(params.KO_DOCKER_REPO) ko publish $(params.MAIN_DIR) | tee /tekton/results/DIGESTS
