#
# MIT License
#
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ko-build-image
spec:
  params:
    - name: MAIN_DIR
      description: Directory containing the main executable (one with main func) to build.
    - name: KO_DOCKER_REPO
      description: Registry to push the image to
  results:
    - name: DIGESTS
      description: Digest of the image just built.
  workspaces:
    - name: source
      description: Where the dependencies and source code are.
  steps:
    - name: ko-build-image
      image: ghcr.io/google/ko:0187841b164187cd835eb96519d5e282d69ca688
      env:
        - name: KO_DOCKER_REPO
          value: $(params.KO_DOCKER_REPO)
        - name: GOMODCACHE
          value: $(workspaces.source.path)/gomod
      resources:
        requests:
          memory: 1Gi
          cpu: 1
        limits:
          memory: 2Gi
          cpu: 1
      script: |
        cd $(workspaces.source.path)/source
        # Strip the trailing newline so hilarity will not ensue in
        # following tasks.
        ko publish $(params.MAIN_DIR) | tr -d '\n' | tee /tekton/results/DIGESTS
