apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: install-python-dependencies
spec:
  workspaces:
    - name: source
      description: Where the git clones the repo to.
    - name: dependencies
      description: Where the dependencies are installed into
  steps:
    - name: install-python-requirements
      image: ghcr.io/vaikas/build-playground@sha256:5cc5b2d31abc2f42dbb9c78b1edb7abfd32235b94c0a640bdba7f353fcea9830
      script: |
        cd $(workspaces.source.path)
        python -m venv $(workspaces.dependencies.path)/venv
        pip install -r ./build/requirements.txt
        ls -R $(workspaces.dependencies.path)
