apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-task-storage
spec:
  resources:
    requests:
      storage: 16Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: python-dependencies-storage
spec:
  resources:
    requests:
      storage: 16Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: bare-build-pipeline-run
spec:
  params:
    - name: git-url
      value: "https://github.com/Cray-HPE/csm.git"
      #value: "https://github.com/vaikas/build-playground.git"
    - name: git-revision
      value: "main"
  pipelineRef:
    name: python-build-pipeline
  workspaces:
  - name: git-source # must match workspace name in Pipeline
    persistentVolumeClaim:
      claimName: shared-task-storage # this PVC must already exist
  - name: dependencies # must match workspace name in Pipeline
    persistentVolumeClaim:
      claimName: python-dependencies-storage # this PVC must already exist
