# Copyright 2021 Chainguard, Inc.
apiVersion: v1
kind: List
items:
  - # SPDX-License-Identifier: Apache-2.0
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: checktree
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: checktree
              image: ghcr.io/vaikas/checktree@sha256:74be07a8aa75ae357305b2d907c5041bbdf3412bbe64569e5e3c983e57f62a56
  - # Copyright 2021 Chainguard, Inc.
    # SPDX-License-Identifier: Apache-2.0
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: check-oidc
    spec:
      template:
        spec:
          serviceAccountName: gke-user
          restartPolicy: Never
          containers:
            - name: check-oidc
              image: gcr.io/projectsigstore/cosign:v1.5.1
              args: [ "sign", "--k8s-keychain", "--force", "--fulcio-url", "http://fulcio.fulcio-system.svc", "--rekor-url", "http://rekor.rekor-system.svc", "gcr.io/chainguard-dev/nginx" ]
              env:
                - name: COSIGN_EXPERIMENTAL
                  value: "true"
                - name: SIGSTORE_CT_LOG_PUBLIC_KEY_FILE
                  value: "/var/run/sigstore-root/rootfile.pem"
                - name: COSIGN_REPOSITORY
                  value: "gcr.io/chainguard-dev/nginx"
              volumeMounts:
                - name: oidc-info
                  mountPath: /var/run/sigstore/cosign
                - name: keys
                  mountPath: "/var/run/sigstore-root"
                  readOnly: true
          volumes:
            - name: oidc-info
              projected:
                sources:
                  - serviceAccountToken:
                      path: oidc-token
                      expirationSeconds: 600 # Use as short-lived as possible.
                      audience: sigstore
            - name: keys
              secret:
                secretName: ctlog-public-key
                items:
                  - key: public
                    path: rootfile.pem
