apiVersion: v1
kind: Pod
metadata:
  name: workload-identity-test
  namespace: default
spec:
  serviceAccountName: gke-user
  containers:
    - image: google/cloud-sdk:slim
      name: workload-identity-test
      command: ["sleep","infinity"]
      volumeMounts:
        - name: oidc-info
          mountPath: /var/run/sigstore/cosign
  volumes:
    - name: oidc-info
      projected:
        sources:
          - serviceAccountToken:
              path: oidc-token
              expirationSeconds: 600 # Use as short-lived as possible.
              audience: sigstore