apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-shared-task-storage
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-dependencies-storage
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: go-build-pipeline-run
spec:
  params:
    - name: git-url
      value: "https://github.com/vaikas/spiffefulciotest.git"
    - name: git-revision
      value: "main"
    - name: MAIN_DIR
      value: "./cmd"
    - name: SIGSTORE_CT_LOG_PUBLIC_KEY_FILE
      value: "/data/ctlog-public.pem"
    - name: KO_DOCKER_REPO
      value: registry.local:5000/knative/gotest
    - name: fulcio-endpoint
      value: "http://fulcio.fulcio-system.svc"
    - name: rekor-endpoint
      value: "http://rekor.rekor-system.svc"
  pipelineRef:
    name: go-build-pipeline
  workspaces:
  - name: git-source # must match workspace name in Pipeline
    persistentVolumeClaim:
      claimName: go-shared-task-storage # this PVC must already exist
  - name: dependencies # must match workspace name in Pipeline
    persistentVolumeClaim:
      claimName: go-dependencies-storage # this PVC must already exist
