apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: list-dependencies
spec:
  workspaces:
    - name: dependencies
      description: Where the dependencies are installed into by previous step
  steps:
    - name: list-python-requirements
      image: ghcr.io/vaikas/build-playground@sha256:1de8e01eaa635a852a720a775f0480356ac82302089a911e1f32cef959235731
      script: |
        cd $(workspaces.dependencies.path)
        ls -R $(workspaces.dependencies.path)
