apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: install-python-dependencies
spec:
  workspaces:
    - name: source
      description: Where the git clones the repo to.
    - name: dependencies
      description: Where the dependencies are installed into
  steps:
    - name: install-python-requirements
      image: python:3.10-slim@sha256:ca2a31f21938f24bab02344bf846a90cc2bff5bd0e5a53b24b5dfcb4519ea8a3
      script: |
        cd $(workspaces.source.path)
        VIRTUAL_ENV=$(workspaces.dependencies.path)/venv
        python3 -m venv $VIRTUAL_ENV
        PATH="$VIRTUAL_ENV/bin:$PATH"
        pip install -r ./build/requirements.txt
        ls -R $(workspaces.dependencies.path)
