apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-task-storage
spec:
  resources:
    requests:
      storage: 16Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: python-dependencies-storage
spec:
  resources:
    requests:
      storage: 16Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-pipeline-run
spec:
  serviceAccountName: gke-user
  params:
    - name: git-url
      value: "https://github.com/Cray-HPE/csm.git"
    - name: git-revision
      value: "main"
    - name: imageUrl
      value: "gcr.io/chainguard-dev/pythontest"
    - name: imageTag
      value: "0.1"
    - name: fulcio-endpoint
      value: "http://fulcio.fulcio-system.svc"
    - name: rekor-endpoint
      value: "http://rekor.rekor-system.svc"
  pipelineRef:
    name: python-build-pipeline
  workspaces:
  - name: git-source # must match workspace name in Pipeline
    persistentVolumeClaim:
      claimName: shared-task-storage # this PVC must already exist
  - name: dependencies # must match workspace name in Pipeline
    persistentVolumeClaim:
      claimName: python-dependencies-storage # this PVC must already exist
  - name: dockerfile-cm
    configMap:
      name: dockerfile
      items:
      - key: Dockerfile
        path: Dockerfile
